-- LaunchPulse · Supabase schema
-- Run this in the Supabase SQL Editor (Dashboard → SQL Editor → New query)

-- Products table
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null unique,
  launch_date date not null,
  notes text default '',
  status text default 'active' check (status in ('active', 'completed')),
  created_at timestamptz default now()
);

-- Per-phase notes
create table if not exists public.phase_notes (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  phase int not null check (phase between 1 and 3),
  content text default '',
  updated_at timestamptz default now(),
  unique (product_id, phase)
);

-- Enable Row Level Security (optional but recommended)
alter table public.products enable row level security;
alter table public.phase_notes enable row level security;

-- Simple policies: any authenticated user can do everything
-- (tighten later for multi-tenant if needed)
create policy "Authenticated full access on products"
  on public.products
  for all
  to authenticated
  using (true)
  with check (true);

create policy "Authenticated full access on phase_notes"
  on public.phase_notes
  for all
  to authenticated
  using (true)
  with check (true);

-- Optional: allow the anon key to read (not needed if you always use authenticated sessions)
-- create policy "Public read products" on public.products for select to anon using (true);

-- Activity log (for drag-drop & advance events)
create table if not exists public.activity_log (
  id bigint generated by default as identity primary key,
  product_id bigint references public.products(id) on delete set null,
  message text not null,
  created_at timestamptz default now()
);

alter table public.activity_log enable row level security;

create policy "Authenticated full access on activity_log"
  on public.activity_log
  for all
  to authenticated
  using (true)
  with check (true);

-- Thumbnail URL on products
alter table public.products add column if not exists thumbnail_url text default '';

-- Keywords on phase_notes
alter table public.phase_notes add column if not exists keywords text default '';

-- ASIN + daily buys plan
alter table public.products add column if not exists asin text default '';
alter table public.products add column if not exists daily_buys jsonb default '{}'::jsonb;

alter table public.products add column if not exists daily_buys_actual jsonb default '{}'::jsonb;

-- Profiles for roles
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  role text default 'user' check (role in ('admin', 'user')),
  created_at timestamptz default now()
);

alter table public.profiles enable row level security;
drop policy if exists "Allow all profiles" on public.profiles;
create policy "Allow all profiles" on public.profiles for all using (true) with check (true);

-- Expand activity_log
alter table public.activity_log add column if not exists user_id uuid;
alter table public.activity_log add column if not exists user_email text;
alter table public.activity_log add column if not exists action text default 'update';


-- BA / Emails workspace sheets (per product)
create table if not exists public.workspace_sheets (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  sheet_type text not null check (sheet_type in ('ba', 'emails')),
  created_at timestamptz default now(),
  unique (product_id, sheet_type)
);

create table if not exists public.workspace_columns (
  id bigint generated by default as identity primary key,
  sheet_id bigint not null references public.workspace_sheets(id) on delete cascade,
  name text not null,
  position int not null default 0,
  created_at timestamptz default now()
);

create table if not exists public.workspace_rows (
  id bigint generated by default as identity primary key,
  sheet_id bigint not null references public.workspace_sheets(id) on delete cascade,
  position int not null default 0,
  color text default 'none' check (color in ('none', 'green', 'red', 'orange')),
  data jsonb default '{}'::jsonb,
  updated_at timestamptz default now(),
  updated_by text
);

alter table public.workspace_sheets enable row level security;
alter table public.workspace_columns enable row level security;
alter table public.workspace_rows enable row level security;

drop policy if exists "Allow all workspace_sheets" on public.workspace_sheets;
create policy "Allow all workspace_sheets" on public.workspace_sheets for all using (true) with check (true);
drop policy if exists "Allow all workspace_columns" on public.workspace_columns;
create policy "Allow all workspace_columns" on public.workspace_columns for all using (true) with check (true);
drop policy if exists "Allow all workspace_rows" on public.workspace_rows;
create policy "Allow all workspace_rows" on public.workspace_rows for all using (true) with check (true);

alter table public.profiles add column if not exists totp_secret text default '';
alter table public.profiles add column if not exists totp_enabled boolean default false;

alter table public.products add column if not exists price numeric(12,2);

-- Allow reviews sheet type
alter table public.workspace_sheets drop constraint if exists workspace_sheets_sheet_type_check;
alter table public.workspace_sheets add constraint workspace_sheets_sheet_type_check
  check (sheet_type in ('ba', 'emails', 'reviews'));

-- Pre-launch step status per product: {step_key: {status, note}}
alter table public.products add column if not exists prelaunch jsonb default '{}'::jsonb;
